@Copilot.SquadAgent.StickerManager.Infrastructure_HostAddress = http://localhost:5149

GET {{Copilot.SquadAgent.StickerManager.Infrastructure_HostAddress}}/weatherforecast/
Accept: application/json

###
