// <auto-generated />
using System;
using Copilot.SquadAgent.StickerManager.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Copilot.SquadAgent.StickerManager.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260514120000_AlterStickersNumberToCode")]
    partial class AlterStickersNumberToCode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Copilot.SquadAgent.StickerManager.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("Copilot.SquadAgent.StickerManager.Domain.Entities.Sticker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("player_name");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("rarity");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_stickers_team_id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_stickers_code");

                    b.ToTable("stickers", (string)null);
                });

            modelBuilder.Entity("Copilot.SquadAgent.StickerManager.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("code")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("FlagUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("flag_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("Copilot.SquadAgent.StickerManager.Domain.Entities.TradeOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_trade_offers_user_id");

                    b.ToTable("trade_offers", (string)null);
                });

            modelBuilder.Entity("Copilot.SquadAgent.StickerManager.Domain.Entities.TradeOfferItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("direction");

                    b.Property<Guid>("StickerId")
                        .HasColumnType("uuid")
                        .HasColumnName("sticker_id");

                    b.Property<Guid>("TradeOfferId")
                        .HasColumnType("uuid")
                        .HasColumnName("trade_offer_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("StickerId");

                    b.HasIndex("TradeOfferId")
                        .HasDatabaseName("ix_trade_offer_items_trade_offer_id");

                    b.ToTable("trade_offer_items", (string)null);
                });

            modelBuilder.Entity("Copilot.SquadAgent.StickerManager.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Copilot.SquadAgent.StickerManager.Domain.Entities.UserCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("QuantityDuplicate")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_duplicate");

                    b.Property<int>("QuantityOwned")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_owned");

                    b.Property<Guid>("StickerId")
                        .HasColumnType("uuid")
                        .HasColumnName("sticker_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("StickerId")
                        .HasDatabaseName("ix_user_collections_sticker_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_collections_user_id");

                    b.HasIndex("UserId", "StickerId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_collections_user_id_sticker_id");

                    b.ToTable("user_collections", (string)null);
                });

            modelBuilder.Entity("Copilot.SquadAgent.StickerManager.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("Copilot.SquadAgent.StickerManager.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Copilot.SquadAgent.StickerManager.Domain.Entities.Sticker", b =>
                {
                    b.HasOne("Copilot.SquadAgent.StickerManager.Domain.Entities.Team", "Team")
                        .WithMany("Stickers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stickers_team_id");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Copilot.SquadAgent.StickerManager.Domain.Entities.TradeOffer", b =>
                {
                    b.HasOne("Copilot.SquadAgent.StickerManager.Domain.Entities.User", "User")
                        .WithMany("TradeOffers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trade_offers_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Copilot.SquadAgent.StickerManager.Domain.Entities.TradeOfferItem", b =>
                {
                    b.HasOne("Copilot.SquadAgent.StickerManager.Domain.Entities.Sticker", "Sticker")
                        .WithMany("TradeOfferItems")
                        .HasForeignKey("StickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trade_offer_items_sticker_id");

                    b.HasOne("Copilot.SquadAgent.StickerManager.Domain.Entities.TradeOffer", "TradeOffer")
                        .WithMany("Items")
                        .HasForeignKey("TradeOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trade_offer_items_trade_offer_id");

                    b.Navigation("Sticker");

                    b.Navigation("TradeOffer");
                });

            modelBuilder.Entity("Copilot.SquadAgent.StickerManager.Domain.Entities.UserCollection", b =>
                {
                    b.HasOne("Copilot.SquadAgent.StickerManager.Domain.Entities.Sticker", "Sticker")
                        .WithMany("UserCollections")
                        .HasForeignKey("StickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_collections_sticker_id");

                    b.HasOne("Copilot.SquadAgent.StickerManager.Domain.Entities.User", "User")
                        .WithMany("UserCollections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_collections_user_id");

                    b.Navigation("Sticker");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Copilot.SquadAgent.StickerManager.Domain.Entities.Sticker", b =>
                {
                    b.Navigation("TradeOfferItems");

                    b.Navigation("UserCollections");
                });

            modelBuilder.Entity("Copilot.SquadAgent.StickerManager.Domain.Entities.Team", b =>
                {
                    b.Navigation("Stickers");
                });

            modelBuilder.Entity("Copilot.SquadAgent.StickerManager.Domain.Entities.TradeOffer", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Copilot.SquadAgent.StickerManager.Domain.Entities.User", b =>
                {
                    b.Navigation("TradeOffers");

                    b.Navigation("UserCollections");
                });
#pragma warning restore 612, 618
        }
    }
}
